using UnityEngine;
using UnityEngine.UI;
using TMPro;
using PrisonIsland.Core;

namespace PrisonIsland.UI
{
    /// <summary>
    /// Générateur automatique d'UI pour tester les systèmes
    /// UTILISATION: Attacher ce script à un GameObject et lancer le jeu
    /// </summary>
    public class AutoUIGenerator : MonoBehaviour
    {
        [Header("Configuration")]
        [SerializeField] private bool autoGenerateOnStart = true;
        [SerializeField] private KeyCode generateKey = KeyCode.G;

        private GameObject mainCanvas;
        private GameObject mainMenu;

        void Start()
        {
            if (autoGenerateOnStart)
            {
                GenerateCompleteUI();
            }
        }

        void Update()
        {
            if (Input.GetKeyDown(generateKey))
            {
                GenerateCompleteUI();
            }
        }

        [ContextMenu("Generate UI")]
        public void GenerateCompleteUI()
        {
            Debug.Log("🎨 Génération automatique de l'UI...");

            // Supprimer l'ancien canvas si existe
            if (mainCanvas != null)
            {
                DestroyImmediate(mainCanvas);
            }

            CreateCanvas();
            CreateMainMenu();
            CreateLeaderboardPanel();
            CreateQuestPanel();
            CreateSettingsPanel();

            Debug.Log("✅ UI générée avec succès!");
            Debug.Log("📋 Appuyez sur les boutons dans le coin supérieur gauche!");
        }

        #region Canvas Creation

        private void CreateCanvas()
        {
            // Créer le Canvas principal
            mainCanvas = new GameObject("AutoGeneratedCanvas");
            Canvas canvas = mainCanvas.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;

            CanvasScaler scaler = mainCanvas.AddComponent<CanvasScaler>();
            scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
            scaler.referenceResolution = new Vector2(1080, 1920); // Mobile portrait

            mainCanvas.AddComponent<GraphicRaycaster>();

            Debug.Log("✅ Canvas créé");
        }

        #endregion

        #region Main Menu

        private void CreateMainMenu()
        {
            mainMenu = new GameObject("MainMenu");
            mainMenu.transform.SetParent(mainCanvas.transform, false);

            RectTransform rt = mainMenu.AddComponent<RectTransform>();
            rt.anchorMin = new Vector2(0, 1);
            rt.anchorMax = new Vector2(0, 1);
            rt.pivot = new Vector2(0, 1);
            rt.anchoredPosition = new Vector2(20, -20);
            rt.sizeDelta = new Vector2(300, 500);

            // Background
            Image bg = mainMenu.AddComponent<Image>();
            bg.color = new Color(0.2f, 0.2f, 0.2f, 0.9f);

            // Titre
            CreateText(mainMenu, "Prison Island Manager", new Vector2(0, -30), new Vector2(280, 50), 24, Color.white, TextAlignmentOptions.Center);

            // Boutons
            CreateButton(mainMenu, "📊 Leaderboards", new Vector2(0, -100), () => OpenLeaderboard());
            CreateButton(mainMenu, "📋 Quests", new Vector2(0, -170), () => OpenQuests());
            CreateButton(mainMenu, "⚙️ Settings", new Vector2(0, -240), () => OpenSettings());
            CreateButton(mainMenu, "🔄 Test Systems", new Vector2(0, -310), () => TestAllSystems());

            // Info text
            CreateText(mainMenu, "Appuyez L, Q, F, E\npour tester par clavier",
                new Vector2(0, -400), new Vector2(280, 80), 14, Color.yellow, TextAlignmentOptions.Center);

            Debug.Log("✅ Menu principal créé");
        }

        #endregion

        #region Leaderboard Panel

        private void CreateLeaderboardPanel()
        {
            GameObject panel = CreatePanel("LeaderboardPanel", "🏆 LEADERBOARDS", new Vector2(0.5f, 0.5f));

            // Content area
            GameObject content = new GameObject("Content");
            content.transform.SetParent(panel.transform, false);
            RectTransform contentRT = content.AddComponent<RectTransform>();
            contentRT.anchorMin = new Vector2(0.05f, 0.15f);
            contentRT.anchorMax = new Vector2(0.95f, 0.85f);
            contentRT.offsetMin = Vector2.zero;
            contentRT.offsetMax = Vector2.zero;

            // Scroll area pour les entries
            GameObject scrollArea = new GameObject("ScrollArea");
            scrollArea.transform.SetParent(content.transform, false);
            RectTransform scrollRT = scrollArea.AddComponent<RectTransform>();
            scrollRT.anchorMin = Vector2.zero;
            scrollRT.anchorMax = Vector2.one;
            scrollRT.offsetMin = Vector2.zero;
            scrollRT.offsetMax = Vector2.zero;

            Image scrollBg = scrollArea.AddComponent<Image>();
            scrollBg.color = new Color(0.1f, 0.1f, 0.1f, 0.5f);

            // Attacher LeaderboardUI si disponible
            LeaderboardUI leaderboardUI = panel.GetComponent<LeaderboardUI>();
            if (leaderboardUI == null)
            {
                leaderboardUI = panel.AddComponent<LeaderboardUI>();
            }

            // Bouton refresh
            CreateButton(panel, "🔄 Refresh", new Vector2(0, -450), () => RefreshLeaderboard());

            // Bouton close
            CreateButton(panel, "✖ Fermer", new Vector2(0, -520), () => panel.SetActive(false));

            panel.SetActive(false);
            Debug.Log("✅ Panneau Leaderboard créé");
        }

        #endregion

        #region Quest Panel

        private void CreateQuestPanel()
        {
            GameObject panel = CreatePanel("QuestPanel", "📋 MISSIONS & QUÊTES", new Vector2(0.5f, 0.5f));

            // Content area
            GameObject content = new GameObject("Content");
            content.transform.SetParent(panel.transform, false);
            RectTransform contentRT = content.AddComponent<RectTransform>();
            contentRT.anchorMin = new Vector2(0.05f, 0.15f);
            contentRT.anchorMax = new Vector2(0.95f, 0.85f);
            contentRT.offsetMin = Vector2.zero;
            contentRT.offsetMax = Vector2.zero;

            // Info text
            GameObject infoText = CreateText(content, "Appuyez P pour progresser une quête",
                new Vector2(0, 0), new Vector2(600, 400), 16, Color.white, TextAlignmentOptions.TopLeft);

            // Attacher QuestUI si disponible
            QuestUI questUI = panel.GetComponent<QuestUI>();
            if (questUI == null)
            {
                questUI = panel.AddComponent<QuestUI>();
            }

            // Boutons
            CreateButton(panel, "📈 Progresser Quest Test", new Vector2(0, -450), () => ProgressTestQuest());
            CreateButton(panel, "✖ Fermer", new Vector2(0, -520), () => panel.SetActive(false));

            panel.SetActive(false);
            Debug.Log("✅ Panneau Quests créé");
        }

        #endregion

        #region Settings Panel

        private void CreateSettingsPanel()
        {
            GameObject panel = CreatePanel("SettingsPanel", "⚙️ PARAMÈTRES", new Vector2(0.5f, 0.5f));

            // Content
            GameObject content = new GameObject("Content");
            content.transform.SetParent(panel.transform, false);
            RectTransform contentRT = content.AddComponent<RectTransform>();
            contentRT.anchorMin = new Vector2(0.05f, 0.2f);
            contentRT.anchorMax = new Vector2(0.95f, 0.85f);
            contentRT.offsetMin = Vector2.zero;
            contentRT.offsetMax = Vector2.zero;

            // Language buttons
            CreateText(content, "🌍 LANGUE / LANGUAGE:", new Vector2(0, -20), new Vector2(600, 40), 18, Color.white, TextAlignmentOptions.Left);

            CreateButton(content, "🇫🇷 Français", new Vector2(0, -80), () => ChangeLanguage(SystemLanguage.French));
            CreateButton(content, "🇬🇧 English", new Vector2(0, -150), () => ChangeLanguage(SystemLanguage.English));
            CreateButton(content, "🇪🇸 Español", new Vector2(0, -220), () => ChangeLanguage(SystemLanguage.Spanish));
            CreateButton(content, "🇩🇪 Deutsch", new Vector2(0, -290), () => ChangeLanguage(SystemLanguage.German));

            // Close button
            CreateButton(panel, "✖ Fermer", new Vector2(0, -520), () => panel.SetActive(false));

            panel.SetActive(false);
            Debug.Log("✅ Panneau Settings créé");
        }

        #endregion

        #region Helper Functions

        private GameObject CreatePanel(string name, string title, Vector2 anchorPosition)
        {
            GameObject panel = new GameObject(name);
            panel.transform.SetParent(mainCanvas.transform, false);

            RectTransform rt = panel.AddComponent<RectTransform>();
            rt.anchorMin = new Vector2(0.5f, 0.5f);
            rt.anchorMax = new Vector2(0.5f, 0.5f);
            rt.pivot = new Vector2(0.5f, 0.5f);
            rt.anchoredPosition = Vector2.zero;
            rt.sizeDelta = new Vector2(700, 600);

            // Background
            Image bg = panel.AddComponent<Image>();
            bg.color = new Color(0.15f, 0.15f, 0.15f, 0.95f);

            // Title
            GameObject titleObj = CreateText(panel, title, new Vector2(0, 270), new Vector2(680, 50), 28, Color.yellow, TextAlignmentOptions.Center);

            return panel;
        }

        private GameObject CreateText(GameObject parent, string text, Vector2 position, Vector2 size, int fontSize, Color color, TextAlignmentOptions alignment)
        {
            GameObject textObj = new GameObject("Text_" + text.Substring(0, Mathf.Min(10, text.Length)));
            textObj.transform.SetParent(parent.transform, false);

            RectTransform rt = textObj.AddComponent<RectTransform>();
            rt.anchorMin = new Vector2(0.5f, 0.5f);
            rt.anchorMax = new Vector2(0.5f, 0.5f);
            rt.pivot = new Vector2(0.5f, 0.5f);
            rt.anchoredPosition = position;
            rt.sizeDelta = size;

            TextMeshProUGUI tmp = textObj.AddComponent<TextMeshProUGUI>();
            tmp.text = text;
            tmp.fontSize = fontSize;
            tmp.color = color;
            tmp.alignment = alignment;

            return textObj;
        }

        private GameObject CreateButton(GameObject parent, string text, Vector2 position, System.Action onClick)
        {
            GameObject btnObj = new GameObject("Button_" + text);
            btnObj.transform.SetParent(parent.transform, false);

            RectTransform rt = btnObj.AddComponent<RectTransform>();
            rt.anchorMin = new Vector2(0.5f, 0.5f);
            rt.anchorMax = new Vector2(0.5f, 0.5f);
            rt.pivot = new Vector2(0.5f, 0.5f);
            rt.anchoredPosition = position;
            rt.sizeDelta = new Vector2(280, 50);

            Image img = btnObj.AddComponent<Image>();
            img.color = new Color(0.3f, 0.5f, 0.8f, 1f);

            Button btn = btnObj.AddComponent<Button>();
            btn.targetGraphic = img;

            // Color animation
            ColorBlock colors = btn.colors;
            colors.normalColor = new Color(0.3f, 0.5f, 0.8f, 1f);
            colors.highlightedColor = new Color(0.4f, 0.6f, 0.9f, 1f);
            colors.pressedColor = new Color(0.2f, 0.4f, 0.7f, 1f);
            btn.colors = colors;

            if (onClick != null)
            {
                btn.onClick.AddListener(() => onClick());
            }

            // Text
            GameObject textObj = new GameObject("Text");
            textObj.transform.SetParent(btnObj.transform, false);

            RectTransform textRT = textObj.AddComponent<RectTransform>();
            textRT.anchorMin = Vector2.zero;
            textRT.anchorMax = Vector2.one;
            textRT.offsetMin = Vector2.zero;
            textRT.offsetMax = Vector2.zero;

            TextMeshProUGUI tmp = textObj.AddComponent<TextMeshProUGUI>();
            tmp.text = text;
            tmp.fontSize = 18;
            tmp.color = Color.white;
            tmp.alignment = TextAlignmentOptions.Center;

            return btnObj;
        }

        #endregion

        #region Button Actions

        private void OpenLeaderboard()
        {
            GameObject panel = GameObject.Find("LeaderboardPanel");
            if (panel != null)
            {
                panel.SetActive(true);
                Debug.Log("📊 Leaderboard ouvert");

                // Test: Submit random score
                if (LeaderboardManager.Instance != null)
                {
                    LeaderboardManager.Instance.SubmitScore(LeaderboardType.TotalMoney, Random.Range(10000, 100000));
                    RefreshLeaderboard();
                }
            }
        }

        private void OpenQuests()
        {
            GameObject panel = GameObject.Find("QuestPanel");
            if (panel != null)
            {
                panel.SetActive(true);
                Debug.Log("📋 Quests ouvert");

                // Afficher les quests dans la console
                if (QuestManager.Instance != null)
                {
                    var quests = QuestManager.Instance.GetActiveQuests();
                    Debug.Log($"=== QUÊTES ACTIVES ({quests.Count}) ===");
                    foreach (var quest in quests)
                    {
                        Debug.Log($"• {quest.questName}: {quest.currentProgress}/{quest.targetValue} ({quest.GetProgressPercentage():F0}%)");
                    }
                }
            }
        }

        private void OpenSettings()
        {
            GameObject panel = GameObject.Find("SettingsPanel");
            if (panel != null)
            {
                panel.SetActive(true);
                Debug.Log("⚙️ Settings ouvert");
            }
        }

        private void TestAllSystems()
        {
            Debug.Log("=== 🧪 TEST DE TOUS LES SYSTÈMES ===");

            // Test Leaderboards
            if (LeaderboardManager.Instance != null)
            {
                Debug.Log("✅ LeaderboardManager détecté");
                LeaderboardManager.Instance.SubmitScore(LeaderboardType.TotalMoney, Random.Range(50000, 150000));
                Debug.Log("📊 Score aléatoire soumis");
            }
            else
            {
                Debug.LogWarning("❌ LeaderboardManager manquant!");
            }

            // Test Quests
            if (QuestManager.Instance != null)
            {
                Debug.Log("✅ QuestManager détecté");
                var quests = QuestManager.Instance.GetActiveQuests();
                Debug.Log($"📋 Quêtes actives: {quests.Count}");
            }
            else
            {
                Debug.LogWarning("❌ QuestManager manquant!");
            }

            // Test Localization
            if (LocalizationManager.Instance != null)
            {
                Debug.Log("✅ LocalizationManager détecté");
                Debug.Log($"🌍 Langue: {LocalizationManager.Instance.GetCurrentLanguage()}");
                Debug.Log($"🔤 ui_play = '{LocalizationManager.Instance.GetText("ui_play")}'");
            }
            else
            {
                Debug.LogWarning("❌ LocalizationManager manquant!");
            }

            Debug.Log("=== TEST TERMINÉ ===");
        }

        private void RefreshLeaderboard()
        {
            if (LeaderboardManager.Instance != null)
            {
                var entries = LeaderboardManager.Instance.GetLeaderboard(LeaderboardType.TotalMoney, 10);
                Debug.Log("=== 🏆 TOP 10 LEADERBOARD ===");
                for (int i = 0; i < entries.Count; i++)
                {
                    Debug.Log($"#{i + 1} {entries[i].playerName}: {entries[i].score:N0}$");
                }
            }
        }

        private void ProgressTestQuest()
        {
            if (QuestManager.Instance != null)
            {
                QuestManager.Instance.UpdateQuestProgress(QuestTargetType.BuildAny, 1);
                Debug.Log("📈 +1 progression sur BuildAny");

                var quests = QuestManager.Instance.GetActiveQuests();
                foreach (var quest in quests)
                {
                    if (quest.targetType == QuestTargetType.BuildAny)
                    {
                        Debug.Log($"✨ {quest.questName}: {quest.currentProgress}/{quest.targetValue}");
                    }
                }
            }
        }

        private void ChangeLanguage(SystemLanguage language)
        {
            if (LocalizationManager.Instance != null)
            {
                LocalizationManager.Instance.SetLanguage(language);
                Debug.Log($"🌍 Langue changée: {language}");

                // Montrer quelques exemples
                Debug.Log($"  ui_play = {LocalizationManager.Instance.GetText("ui_play")}");
                Debug.Log($"  resource_money = {LocalizationManager.Instance.GetText("resource_money")}");
                Debug.Log($"  building_cell = {LocalizationManager.Instance.GetText("building_cell")}");
            }
        }

        #endregion
    }
}
